---
kind: pipeline
name: default

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - "gradle -v"
    environment:
      MAVENUSER:
        from_secret: th_nexus_user
      MAVENPASSWORD:
        from_secret: th_nexus_password