---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:jdk17
    environment:
      MAVENUSER:
        from_secret: th_nexus_user
      MAVENPASSWORD:
        from_secret: th_nexus_password
    commands:
      - gradle assemble
