kind: pipeline
type: docker
name: default


steps:
  - name: build
    image: gradle:jdk17
    commands:
      - gradle publish
    environment:
      MAVENUSER:
        from_secret: th_nexus_user
      MAVENPASSWORD:
        from_secret: th_nexus_password

trigger:
  branch:
    - master
  event:
    - push