kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - gradle publish
    environment:
      MAVEN_USER:
        from_secret: th_nexus_user
      MAVEN_PASSWORD:
        from_secret: th_nexus_password

trigger:
  branch:
    - master
  event:
    - push