---
kind: pipeline
name: default

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - "echo $JAVA_HOME"
      - "ls /opt/java"
    environment:
      MAVENUSER:
        from_secret: th_nexus_user
      MAVENPASSWORD:
        from_secret: th_nexus_password