kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - gradle publish
    environment:
      MAVEN_USER:
        from_secret: th_nexus_user
      MAVEN_PASSWORD:
        from_secret: th_nexus_password
trigger:
  branch:
    - master
  event:
    - push

---

kind: pipeline
type: ssh
name: default

server:
  host:
    from_secret: ssh_host
  user: tobi
  password:
    from_secret: ssh_password

steps:
  - name: deploy
    environment:
      JWT_SECRET:
        from_secret: jwt_secret
      MYSQL_HOST: "mysql"
      COMPOSE_PROJECT_NAME: ar_tool
    commands:
      - docker compose build
      - docker compose up -d

trigger:
  branch:
    - master
  event:
    - push