kind: pipeline
type: ssh
name: deploy_prod_backend

server:
  host:
    from_secret: ssh_host_prod
  user: root
  password:
    from_secret: ssh_password_prod

steps:
  - name: deploy
    environment:
      JWT_SECRET:
        from_secret: jwt_secret
      MYSQL_HOST: "ab-mysql"
      COMPOSE_PROJECT_NAME: webservices
    commands:
      - docker compose -f docker-compose_prod.yaml build
      - docker compose -f docker-compose_prod.yaml up -d

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
type: docker
name: publish_snapshot_artifact

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - gradle publish
    environment:
      MAVEN_USER:
        from_secret: th_nexus_user
      MAVEN_PASSWORD:
        from_secret: th_nexus_password
trigger:
  branch:
    - master
  event:
    - push

---

kind: pipeline
type: ssh
name: deploy_local_dev

server:
  host:
    from_secret: ssh_host_local_dev
  user: tobi
  password:
    from_secret: ssh_password_local_dev

steps:
  - name: deploy
    environment:
      JWT_SECRET:
        from_secret: jwt_secret
      MYSQL_HOST: "mysql"
      COMPOSE_PROJECT_NAME: ar_tool
    commands:
      - docker compose build
      - docker compose up -d

trigger:
  branch:
    - dev
  event:
    - push