version: "3.9"
services:
  mysql:
    image: mysql:8.0.26
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=asset_rebalancer
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - vmysql:/var/lib/mysql

volumes:
  vmysql: