version: "3.9"
services:
  runner:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - JWT_SECRET=${JWT_SECRET:-devSecret}
    networks:
      - ar_net

networks:
  ar_net:
    external: true