version: "3.9"

services:
  dbrunner:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - JWT_SECRET=${JWT_SECRET:-devSecret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - ar_net

networks:
  ar_net:
    external: true