version: "3.9"

services:
  mysql:
    restart: always
    image: mysql:8.0.26
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=asset_rebalancer
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - vmysql:/var/lib/mysql
    networks:
      - ar_net
  dbrunner:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - JWT_SECRET=${JWT_SECRET:-devSecret}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    networks:
      - ar_net

networks:
  ar_net:
    external: true

volumes:
  vmysql: